### ISSUE TITLE
Plán lekcí: `sessions` nebo `plan`?

### ISSUE THREAD

**Issue by befeleme** [pyvec/naucse-python#18]
Instrukce ohledně sestavení plánu lekcí matou neznalce :)
Zde: https://naucse.python.cz/course/meta/meta/local-run/#header-plan_lekci je informace, že se lekce kurzu definují pomocí klíče `sessions` - poslední příklad v tomto návodu však používá `plan`. 
Vzorová šablona připravená pro stažení zde: https://naucse.python.cz/course/meta/meta/local-run/#header-definice_kurzu také obsahuje klíč `plan`. Není jasné, která z variant je správná, obě se zdají fungovat správně.

**Comment by encukou** [comment]
`sessions`. `plan` je staré jméno, časem přestane fungovat.
